name: Deploy to GitHub Pages

# 仅在推送到 main 分支时触发
on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发 workflow
# 设置执行的工作
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 检查代码库
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      # 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm

     # 安装依赖
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      # 运行 build 指令
      - name: Run build
        run: pnpm run --filter @chapanda/style-preset-interactive-client build:docs

      # 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          # 部署 dist/interactive/client 目录中的内容
          publish_dir: dist/interactive/client
